=== boracs/Ejercicio-JAVA-concesionario/history/concessionaire.dtd
<!ELEMENT concessionaire (cars,trucks)>
<!ELEMENT cars (car*)>
<!ELEMENT car (brand,model,year,registration,numFrame,colour,numOfSeats,price,numDoors,trunkCapacity)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT registration (#PCDATA)>
<!ELEMENT numFrame (#PCDATA)>
<!ELEMENT colour (#PCDATA)>
<!ELEMENT numOfSeats (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT numDoors (#PCDATA)>
<!ELEMENT trunkCapacity (#PCDATA)>
<!ELEMENT trucks (truck*)>
<!ELEMENT truck (brand,model,year,registration,numFrame,colour,numOfSeats,price,load,merchandiseType)>
<!ELEMENT load (#PCDATA)>
<!ELEMENT merchandiseType (#PCDATA)>

=== boracs/Ejercicio-JAVA-concesionario/history/concessionaire.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE concessionaire SYSTEM "concessionaire.dtd">
<concessionaire>
    <cars>
      <car>
        <brand>Ford</brand>
        <model>Mustang Shelby GT500</model>
        <year>1967</year>
        <registration>12345</registration>
        <numFrame>12345678901234567</numFrame>
        <colour>grey and blue</colour>
        <numOfSeats>2</numOfSeats>
        <price>95000</price>
        <numDoors>2</numDoors>
        <trunkCapacity>120</trunkCapacity>
      </car>
      <car>
        <brand>Renault</brand>
        <model>Alpine</model>
        <year>1984</year>
        <registration>310ALP</registration>
        <numFrame>98765432101234567</numFrame>
        <colour>red</colour>
        <numOfSeats>2</numOfSeats>
        <price>45000</price>
        <numDoors>2</numDoors>
        <trunkCapacity>0</trunkCapacity>
      </car>
    </cars>
    <trucks>
      <truck>
        <brand>Volkswagen</brand>
        <model>California t2</model>
        <year>1967</year>
        <registration>VW00CAL</registration>
        <numFrame>lkgtrvg2678452gt9</numFrame>
        <colour>orange</colour>
        <numOfSeats>7</numOfSeats>
        <price>70000</price>
        <load>300</load>
        <merchandiseType>A</merchandiseType>
      </truck>
      <truck>
        <brand>Volkswagen</brand>
        <model>California</model>
        <year>1950</year>
        <registration>VWT1950</registration>
        <numFrame>lkgtrvg2678452gt9</numFrame>
        <colour>pink</colour>
        <numOfSeats>7</numOfSeats>
        <price>180000</price>
        <load>700</load>
        <merchandiseType>A</merchandiseType>
      </truck>
    </trucks>
  </concessionaire>
